insert into lobby.players (nickname, vehicle_type, creation_time) values
('##Abel#%', 1, current_timestamp),
('##Abel$-', 2, current_timestamp),
('##Abel}@', 3, TO_TIMESTAMP('2021-07-01', 'YYYY-MM-DD')),
('##Abel#%1', 1, current_timestamp),
('##Abel$-1', 2, current_timestamp),
('##Abel}@1', 3, TO_TIMESTAMP('2021-08-01', 'YYYY-MM-DD')),
('##Abel#%2', 1, current_timestamp),
('##Abel$-2', 2, current_timestamp),
('##Abel}@2', 3, TO_TIMESTAMP('2021-06-01', 'YYYY-MM-DD')),
('##Abel#%3', 1, current_timestamp),
('##Abel$-3', 2, current_timestamp),
('##Abel}@3', 3, current_timestamp),
('##Abel#%4', 1, current_timestamp),
('##Abel$-4', 2, current_timestamp),
('##Abel}@4', 3, TO_TIMESTAMP('2021-03-01', 'YYYY-MM-DD')),
('##Abel#%5', 1, current_timestamp),
('##Abel$-5', 2, current_timestamp),
('##Abel}@5', 3, TO_TIMESTAMP('2021-05-01', 'YYYY-MM-DD')),
('##Abel#%6', 1, current_timestamp),
('##Abel$-6', 2, current_timestamp),
('##Abel}@6', 3, TO_TIMESTAMP('2021-04-01', 'YYYY-MM-DD'));
